"""five tables

Revision ID: dc7413bb4fc1
Revises: 
Create Date: 2026-09-28 00:47:20.715835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7413bb4fc1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=True),
    sa.Column('resume_json', sa.JSON(), nullable=True),
    sa.Column('jd_json', sa.JSON(), nullable=True),
    sa.Column('coverage_map', sa.JSON(), nullable=True),
    sa.Column('problem_id', sa.String(length=64), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_state'), 'sessions', ['state'], unique=False)
    op.create_table('code_snaps',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('session_id', sa.String(length=12), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_snaps_session_id'), 'code_snaps', ['session_id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('session_id', sa.String(length=12), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('speaker', sa.String(length=12), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('t_start', sa.Float(), nullable=False),
    sa.Column('t_end', sa.Float(), nullable=False),
    sa.Column('ttft_ms', sa.Integer(), nullable=True),
    sa.Column('think_ms', sa.Integer(), nullable=True),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_session_id'), 'turns', ['session_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('turn_id', sa.String(length=12), nullable=False),
    sa.Column('route', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_turn_id'), 'decisions', ['turn_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('turn_id', sa.String(length=12), nullable=False),
    sa.Column('dimension', sa.String(length=48), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('evidence_span', sa.Text(), nullable=False),
    sa.Column('ideal_answer', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_turn_id'), 'evaluations', ['turn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_turn_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_decisions_turn_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_turns_session_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_code_snaps_session_id'), table_name='code_snaps')
    op.drop_table('code_snaps')
    op.drop_index(op.f('ix_sessions_state'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
